FROM node:24-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache netcat-openbsd


ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

CMD ["npm", "run", "start:dev"]
